# Dependencies
markdown:           kramdown
highlighter:        true

# Permalinks
permalink:          /:title

# Site settings
title:              Matthew Strickland
tagline:          	
email:              matthew@idlefusion.com
url:                http://mstrick.com
paginate:           10
baseurl:            
author:
  name:             Matthew Strickland
  url:              https://twitter.com/strickland
  email:            matthew@idlefusion.com
  twitter: 		      strickland
  github:           mps

# Custom vars