# Dependencies
markdown:           kramdown
highlighter:        true

# Permalinks
permalink:          /:title

# Site settings
title:              Matthew Strickland
tagline:          	
email:              matthew@idlefusion.com
url:                http://mstrick.com
paginate:           5
baseurl:            
author:
  name:             Mark Otto
  url:              https://twitter.com/mdo
  email:            markdotto@gmail.com
  twitter: 		    strickland
  github:           mps

# Custom vars